name = "thedirectory"
compatibility_date = "2024-01-01"
pages_build_output_dir = "public/"

[[kv_namespaces]]
binding = "NOTES"
id = "e013eb47dcb54682aaf5351166b6a78d"

[[kv_namespaces]]
binding = "BOOKMARKS"
id = "f7529fc7048e4600a455cef69252e007"

[[kv_namespaces]]
binding = "LISTS"
id = "aa768322b6fb4eeeb7299f692a9db230"
